apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: app-test-devfile-sample-code-with-quarkus-xnrm-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: app-test-devfile-sample-code-with-quarkus-xnrm-sample
    app.kubernetes.io/part-of: app-test
  name: app-test-devfile-sample-code-with-quarkus-xnrm-sample
  namespace: sbudhwar-1-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: app-test-devfile-sample-code-with-quarkus-xnrm-sample
    weight: 100
status: {}
