apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: app-test-devfile-sample-code-with-quarkus-xnrm-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: app-test-devfile-sample-code-with-quarkus-xnrm-sample
    app.kubernetes.io/part-of: app-test
  name: app-test-devfile-sample-code-with-quarkus-xnrm-sample
  namespace: sbudhwar-1-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: app-test-devfile-sample-code-with-quarkus-xnrm-sample
status:
  loadBalancer: {}
